### ISSUE TITLE
Parentheses in part names cause an error during create vector build plans

### ISSUE THREAD

**Issue by ethanj801** [iGEM-Engineering/iGEM-distribution#151]
Ok. So the issue was in fact with the "(" not with the ".". This is actually preferable because for these particular parts it was not too big of a deal to remove the "(".

_Originally posted by @ethanj801 in https://github.com/iGEM-Engineering/iGEM-distribution/issues/148#issuecomment-1013400923_

Using a name containing a parenthesis causes an error during the create vector build step of the build and validate packages workflow. There is no clear error message associated with the failure.

**Comment by ethanj801** [comment]
Example failed log run attached. 
[logs_14.zip](https://github.com/iGEM-Engineering/iGEM-distribution/files/7872913/logs_14.zip)

To replicate, push a branch containing the attached CRISPR-Cas directory to the repository and run the build and validate packages workflow. The error is resolved when the names `ABE8e(TadA-8e V106W)` and`SaABE8e(TadA-8e V106W)` are changed to `ABE8e TadA-8e V106W` and `SaABE8e TadA-8e V106W`. 

[CRISPR-Cas.zip](https://github.com/iGEM-Engineering/iGEM-distribution/files/7872917/CRISPR-Cas.zip)

**Comment by nickdelkis** [comment]
To pin it down a tad bit more, SBOL translation makes the parentheses look like this:

>https://github.com/iGEM-Engineering/iGEM-distribution/CRISPR-Cas/SaABE8e_LEFT_PARENTHESISTadA_V106W_RIGHT_PARENTHESIS

So maybe replace actual parentheses ( ) with LEFT_PARENTHESIS and RIGHT_PARENTHESIS, respectively?

**Comment by noahsprent** [comment]
I've followed Ethan's instructions to reproduce the bug, and can confirm that this is still an issue as of now:
https://github.com/iGEM-Engineering/iGEM-distribution/runs/7846006038?check_suite_focus=true
